services:
  postgres:
    image: postgres
    container_name: Kuwait-cars-database
    environment:
      - POSTGRES_USER=cars
      - POSTGRES_PASSWORD=cars
      - POSTGRES_DB=kuwait_cars
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
