services:
  postgres:
    image: postgres
    container_name: Kuwait-cars-database
    environment:
      - POSTGRES_USER=kuwait_cars
      - POSTGRES_PASSWORD=kuwait_cars
      - POSTGRES_DB=kuwait_cars
    ports:
      - 5432:5432
    volumes:
      - kuwait_cars_pd_data:/var/lib/postgresql/data

volumes:
  kuwait_cars_pd_data:
