services:
  postgres:
    image: postgres
    container_name: Kuwait-cars-database
    environment:
      - POSTGRES_USER=lms
      - POSTGRES_PASSWORD=lms
      - POSTGRES_DB=lms
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
